### ISSUE TITLE
Use container as index file

### ISSUE THREAD

**Issue by bourgeoa** [linonetwo/solid-tiddlywiki-syncadaptor#4]
I made a test building an __index__.json with only title and date modified skinnytiddlers works without any problems.
I took these from the container. So no need for an index except if you want to load the **tags **without loading the tiddlers

**Comment by linonetwo** [comment]
The question is, is title enough to decide whether TW needs to reload a tiddler?

If you change some tiddler in another device, you may want to reload it depends on some other metadata.

But I agree that container as index file is enough since we can get "modified" from the container, look at https://groups.google.com/forum/#!topic/tiddlywikidev/mgiYWXRy0_E , seems if you only return `title` field, TW will use it to determining whether tiddler has changed in the backend, but if you also return a `modified`(Date) field, it will use it too.

**Comment by linonetwo** [comment]
But load more metadata is not so hard, we can store tiddler fields inside `xxx.meta` files, and:

1. only load `title` and `modified` from the container on the startup.
1. load all metadata use globbing on the second `getSkinnyTiddlers()`, maybe these metadata will be used in searching?
1. only load `title` and `modified` from the container on subsequent `getSkinnyTiddlers()`, only for TW to determine whether to trigger loadTiddler().

FYI to use globbing:

<img width="1015" alt="屏幕快照 2019-05-05 上午8 45 26" src="https://user-images.githubusercontent.com/3746270/57186463-8b611280-6f12-11e9-9471-173c8feaa654.png">

**Comment by linonetwo** [comment]
There are two problems:

1. "modified" field from the server is the time POST reaches the server, but in the client side, it's the time user click save button. So "modified" in the client side will be earlier than that on the server side.
2. "title" contains slash "/", we can't store it directly to the server, we may need to replace "/" with some other characters.

**Comment by bourgeoa** [comment]
I don't have any / in the title. Title is the name of the tiddler and the name of the tiddler file without extension.

I have decided to keep the index file for the time being because when I load the skinnytiddlers without the **tags** these are not loaded through the load tiddler function.

**Comment by bourgeoa** [comment]
I have made a RDF .tll version functional.
Just need to test the migration function.

We must agree to a final commun ontology.

There is a small problem with the  "Draft of 'New tiddler'" that creates 2 vocab **draft.of** and **draft.title**. A dot character being forbidden in ontologies I have converted the dot (draft.) by underscore (draft_).

**Comment by linonetwo** [comment]
Can you reuse some of the existed vocabularies for the draft? Here are some of them https://lov.linkeddata.es/dataset/lov/terms?q=draft

But I dont understand how you are going to use draft.of and draft.title, what is the subject and object?

**Comment by linonetwo** [comment]
Can you reuse some of the existed vocabularies for the draft? Here are some of them https://lov.linkeddata.es/dataset/lov/terms?q=draft

But I dont understand how you are going to use draft.of and draft.title, what is the subject and object?

**Comment by linonetwo** [comment]
<img width="689" alt="屏幕快照 2019-05-10 上午9 03 51" src="https://user-images.githubusercontent.com/3746270/57495889-c55f5980-7302-11e9-96e2-8e32f232e992.png">
Maybe using globbing?

**Comment by linonetwo** [comment]
I'm trying to name all metafile (each contains skinny fields for a tiddler) with pattern `.meta.xxxtiddlername.ttl`, so I can globbing all `.meta.*` so GET them in a single file.

**Comment by linonetwo** [comment]
Actually, just after startup, saveTiddeler() will try to save `$:/StoryList`, so I'm asking how you handle / in the title.

**Comment by linonetwo** [comment]
Some tiddlers don't have the tags, will load tiddler function refused to load them? What did you mean by this?

**Comment by linonetwo** [comment]
<img width="488" alt="屏幕快照 2019-05-10 上午9 23 11" src="https://user-images.githubusercontent.com/3746270/57496386-41f33780-7305-11e9-9795-ad49274b40b4.png">
You can see how node-tiddler handles filename, I think reading all fields from a metafile is a good way to avoid trouble.

**Comment by bourgeoa** [comment]
I never store ``$:/StoryList`` and I think any so called system files ($:/......).

For the filename only I use encodeUriComponent(title).

**Comment by linonetwo** [comment]
Why not? I think some plugin may store some config in the `$:/` tiddlers, and maybe user want to store their configs?

**Comment by linonetwo** [comment]
BTW, I'm trying to use https://github.com/pasqLisena/rdf-translator to translate between JSON and turtle. But it's very slow.

**Comment by bourgeoa** [comment]
For ``draft.of`` and ``draft.title`` they are used as a temporarily duplicate during tiddler edit. As such I considered not using a specific ontology for them but the default one (https://example.org/vocab# or any other name).

Do you know if there is something in RDF spec on the name to use for this default non exist ontology ?

**Comment by linonetwo** [comment]
> Do you know if there is something in RDF spec on the name to use for this default non exist ontology ?

I have no idea, I think it just required to resolve, so a human can read the defination. Maybe you can use `https://tiddlywiki.com/static/DraftMechanism#of` and `https://tiddlywiki.com/static/DraftMechanism#title`.

**Comment by linonetwo** [comment]
I'm using the context you suggested like this:

https://github.com/linonetwo/solid-tiddlywiki-syncadaptor/blob/01c38f661c943ba409bfc4e41891566b1a765350/src/SyncAdaptor.js#L15-L34

https://github.com/linonetwo/solid-tiddlywiki-syncadaptor/blob/01c38f661c943ba409bfc4e41891566b1a765350/src/SyncAdaptor.js#L117-L124
https://github.com/linonetwo/solid-tiddlywiki-syncadaptor/blob/01c38f661c943ba409bfc4e41891566b1a765350/src/SyncAdaptor.js#L168-L171

**Comment by linonetwo** [comment]
What do you mean by:

> when I load the skinnytiddlers without the tags these are not loaded through the load tiddler function.

**Comment by bourgeoa** [comment]
It was in the specific test where I used an index file containing only the title. I do not change anything to the toddler they remained with all there fields.
The skinnytiddlers loaded the list of tiddlers as having no tags. Quite normal. Then I manually select and load a tiddler that has tags.
These tags did not show in the tiddlywiki, neither in the tiddler nor in the tag list.

I did not further explore and decided that skinnytiddlers needed all tiddlerfields except the **text** field.
As I do not load all tiddlers at startup but only on demand, I keep an index file for performance.

**Comment by linonetwo** [comment]
I'm pausing my development waiting issues to resolve:

https://github.com/digitalbazaar/jsonld.js/issues/314
https://github.com/solid/node-solid-server/issues/1186

**Comment by linonetwo** [comment]
How will you name your index file? `index.ttl`? What if a user creates a file named `index.ttl`?

I'd consider using `./meta/xxx.ttl` to store metadata for `./xxx.xx`, just store all metadata in a sub-container, with the same name as the file we want to describe, and use globbing to GET them at once.
If not using globbing, I'd use `./meta/index.ttl`, I'm not sure if this is a good name.

**Comment by bourgeoa** [comment]
This index is a problem for interoperability because :
- it is not a tiddlywiki spec
- if we use different spec, :
-- it will not be updated creating discrepancy
-- if we rebuild it we will not know that the fileindex stays up-to-date.

Not taking in consideration that .meta and blob  don't seem to be firmly in Solid spec.

I am beginning to think we need to build the skinnytiddlers directly from the tiddlers.
Each app choosing his way to do it (reading all files, building simplified skinnytiddlers with LDFLEX, ...).

If the performance is too bad we could look at an other way that would be to have the index reflect the tiddlywiki internal JSON format as I have know. The filename of the index will be a param that will be stored in Solid pod.
For the time being it is named ``__lndex__.json``. (I kept it from the app I used as model)

**Comment by linonetwo** [comment]
I was on some other project since May. I'm going to try to finish solid-tiddlywiki project in June now.

> to build the skinnytiddlers directly from the tiddlers

Yes, that would be the best way. But the problem is, NSS doesn't support cross-file SPARQL now, so if do so, there will be O(n) SPARQL to it. I will try doing so on an HTTP2 connection.

**Comment by linonetwo** [comment]
I will work on https://github.com/linonetwo/solid-tiddlywiki-syncadaptor/issues/3 PWA support first, so every tiddler can be store locally, doing sparql on them will be much more faster.

One thing I need to know is how to do fast diff with server, so it only loads changed tiddlers on the startup.

**Comment by linonetwo** [comment]
Life will be much easier if NSS supports multiple file SPARQL.

**Comment by linonetwo** [comment]
Bugs in NSS seem to be fixed, but there are several new bugs in `solid-auth-client`, pausing until they are fixed:

https://github.com/solid/node-solid-server/issues/1231

**Comment by linonetwo** [comment]
We can use FootPrint! https://www.w3.org/ns/footprints https://ruben.verborgh.org/blog/2019/06/17/shaping-linked-data-apps/#future-shapes

**Comment by linonetwo** [comment]
Now I'm using `xxx.metadata` to store tiddler metadata, and when saving each tiddler `xxx`, I store an `xxx.metadata`. When loading, I load two files at the same time.

Not using `xxx.meta` because NSS is buggy dealing with `xxx.meta`.
